export const CLEAR_OBJCTS = 'CLEAR_OBJCTS';
//Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTOMATIC_LOGIN_SUCCESS = 'AUTOMATIC_LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const LOADING = 'LOADING';

//TRANSACTION SCREEN
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const ADD_A_PRODUCT_TO_BASKET = 'ADD_A_PRODUCT_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_BY_CATEGORY_ID = 'GET_PRODUCTS_BY_CATEGORY_ID';
export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
// F4
export const F4_POST_BALANCE = 'F4_POST_BALANCE';
//personels
export const USERS_ALL = 'USERS_ALL';
export const SAVE_USER = 'SAVE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const SAVE_ERROR = 'SAVE_ERROR';
export const CLEAR_DYNOBJ_USERS = 'CLEAR_DYNOBJ_USERS';
export const CHANGE_LANG = 'CHANGE_LANG';

//BALANCE
export const GET_BALANCE = 'GET_BALANCE';
export const GET_RATINGS = 'GET_RATINGS';
export const CLEAR_RATINGS_BALANCE = 'CLEAR_RATINGS_BALANCE';

//BALANCE
export const GET_CATALOG = 'GET_CATALOG';
export const LOADING_CATALOG = 'LOADING_CATALOG';
